equipos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^equipo/agregar$','equipos.views.agregar', name='agregar_equipo'),
    url(r'^equipo/editar/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/editar/(?P<id>\d+)/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/lista$','equipos.views.lista', name='lista_equipo'),
)

torneos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^cuenta/", include("account.urls")),
    #Include de las aplicaciones de las urls
    url(r'^', include('arbitros.urls', namespace="arbitros")),
    url(r'^', include('campeonatos.urls', namespace="campeonatos")),
    url(r'^', include('complejos.urls', namespace="complejos")),
    url(r'^', include('equipos.urls', namespace="equipos")),
    url(r'^', include('jugadores.urls', namespace="jugadores")),
    url(r'^', include('usuario.urls', namespace="usuarios")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipos/models.py
from django.db import models
from django.utils.encoding import smart_unicode
from complejos.models import Complejo

# Create your models here.
class Equipo(models.Model):
    nombre = models.CharField(max_length=120, null=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    complejo_id = models.ForeignKey(Complejo)

    def __unicode__(self):
        return smart_unicode(self.nombre)

equipos/forms.py
from django import forms

from .models import Equipo

class EquiposForm(forms.ModelForm):
    class Meta:
        model = Equipo

equipos/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.views.generic import TemplateView
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from campeonatos.forms import CampeonatoForm
from campeonatos.models import Campeonato
from complejos.forms import ComplejoPublicForm, ComplejoForm
from complejos.models import Complejo
from equipos.models import Equipo
from equipos.forms import EquiposForm
from django import forms

# Create your views here.
@login_required
def agregar(request):
    logged_user = request.user.id
    if request.method == "POST":
        form = EquiposForm(request.POST)
        if form.is_valid():
            form.save()
            return lista(request)
        else:
            print form.errors
    else:
        form = EquiposForm()
    return render_to_response("equipos/agregar.html", {'form': form, 'user': logged_user}, context_instance=RequestContext(request))

@login_required
def editar(request, id=None):
    #Obtengo el objeto de acuerdo al id
    if id:
        equipo_objeto =  get_object_or_404(Equipo, id=id, complejo_id__user=request.user)
    else:
        equipo_objeto = Equipo(id=request.id)

    if request.method == "POST":
        form = EquiposForm(request.POST, instance=equipo_objeto)
        if form.is_valid():
            form.save()
            return lista(request)
        else:
            print form.errors
    else:
        form = EquiposForm(instance=equipo_objeto)
    #Renderizo la vista y paso el objeto con los valores a editar
    return render_to_response("equipos/editar.html", {'form': form}, context_instance=RequestContext(request))

@login_required
def ver(request, id=None):
    #complejos = Complejo.objects.all().filter(id=id, user__id = request.user.id)
    campeonatos =  get_object_or_404(Campeonato, id=id, complejo_id__user=request.user)
    equipos = Equipo.objects.all().filter(complejo_id=campeonatos.id, complejo_id__user=request.user)
    logged_user = request.user.id
    return render_to_response("equipos/ver.html", {'campeonatos': campeonatos, 'user': logged_user, 'equipos':equipos}, context_instance=RequestContext(request))

@login_required
def lista(request):
    equipos = Equipo.objects.all().filter(complejo_id__user=request.user)
    form = CampeonatoForm()
    logged_user = request.user.id
    return render_to_response("equipos/lista.html", {'form': form, 'user': logged_user, 'equipos':equipos}, context_instance=RequestContext(request))

torneos/templates/equipos/agregar.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    {% if form.errors %}
    <p style="color: red;">
        Por favor corrija los errores.
    </p>
    {% endif %}
    <h2>{% trans "Administración de tus equipos" %}</h2>
    <p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ user }}"/>
            <input type="submit" value="Submit" />
        </form>
    </p>
{% endblock %}

torneos/templates/equipos/editar.html
 {% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    

     <form method="post">{% csrf_token %}

         {{ form.as_p }}

         <input type="hidden" name="id_equipo" value="1"/>
         <a href="#">Cancelar</a> <input type="submit" value="Guardar" />

    </form>
{% endblock %}

torneos/templates/equipos/lista.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h2>{% trans "Administración de tus equipos" %}</h2>

    <p>
        <div class="container">
            <hr>
            <div class="row">
                <div class="panel panel-primary filterable">
                    <div class="panel-heading">
                        <h3 class="panel-title">Equipos
                            <div class="pull-right">
                                <a href="{% url 'equipos:agregar_equipo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Equipo</a>
                           </div>
                        </h3>
                    </div>
                    <table class="table">
                        <thead>
                            <tr class="filters">
                                <th><label>Nombre</label></th>
                                <th><label>Dirección</label></th>
                                <th><label>Teléfono</label></th>
                                <th><label>Editar</label></th>
                                <th><label>Ver</label></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for equipo in  equipos %}
                            <tr>
                                <td>{{ equipo.nombre }}</td>
                                <td>{{ equipo.direccion }}</td>
                                <td>{{ equipo.telefono }}</td>
                                <td>
                                     <a href="{% url 'equipos:editar_equipo' equipo.id %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Editar</a></span>
                                </td>
                                <td>
                                    
                                </td>                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </p>
{% endblock %}

torneos/templates/equipos/ver.html
ver.html