equipos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^equipo/agregar$','equipos.views.agregar', name='agregar_equipo'),
    url(r'^equipo/editar/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/editar/(?P<id>\d+)/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/lista$','equipos.views.lista', name='lista_equipo'),
)

torneos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^cuenta/", include("account.urls")),
    #Include de las aplicaciones de las urls
    url(r'^', include('arbitros.urls', namespace="arbitros")),
    url(r'^', include('campeonatos.urls', namespace="campeonatos")),
    url(r'^', include('complejos.urls', namespace="complejos")),
    url(r'^', include('equipos.urls', namespace="equipos")),
    url(r'^', include('jugadores.urls', namespace="jugadores")),
    url(r'^', include('usuario.urls', namespace="usuarios")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^perfil/$','usuario.views.perfil', name='perfil'),
)

torneos/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Mi Cuenta" %}</a>
        </li>
        <li>
            <a href="{% url 'usuarios:perfil' %}"><i class="fa fa-cog"></i> {% trans "Panel" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Cerrar Sesión" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Registrarse" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

torneos/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2014 &lt;micampeonato.com&gt;" %}

torneos/templates/banner_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body %}
    <div class="jumbotron">
    {% block banner %}
        <h1>Hello, world!</h1>
        <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
    {% endblock %}
    </div>
    

{% endblock %}

torneos/templates/homepage.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h1>{% trans "Welcome to Pinax" %}</h1>
    <p>
        {% blocktrans %}
        <b>Pinax</b> is a <a href="http://djangoproject.com/">Django</a>
        project intended to provide a starting point for websites. By
        integrating numerous reusable Django apps to take care of the
        things that many sites have in common, it lets you focus on what
        makes your site different.
        {% endblocktrans %}
    </p>

    <h2>About Account Project</h2>
    <p>
        {% blocktrans %}
        In addition to what is provided by the "zero" project, this project
        provides thorough integration with django-user-accounts, adding
        comprehensive account management functionality. It is a foundation
        suitable for most sites that have user accounts.
        {% endblocktrans %}
    </p>

    {% if user.is_authenticated %}
        {% url "what_next" as what_next_url %}
        <p class="what_next">{% blocktrans %}Wondering <a href="{{ what_next_url }}" class="btn btn-primary large">What Next</a>?{% endblocktrans %}</p>
    {% else %}
        {% url "account_login" as login_url %}
        {% url "account_signup" as signup_url %}
        <p>{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to try out the site.{% endblocktrans %}</p>
    {% endif %}
{% endblock %}

torneos/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}


{% block style_base %}
    <link href="{% static "pinax/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    {% block extra_style %}{% endblock %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}


{% block script_base %}
    <script src="{% static "js/jquery-1.11.1.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "pinax/js/theme.js" %}"></script>
    {% block extra_script %}{% endblock %}
{% endblock %}