campeonatos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^campeonato/agregar$','campeonatos.views.agregar', name='agregar_torneo'),
    url(r'^campeonato/editar/$','campeonatos.views.editar', name='editar_torneo'),
    url(r'^campeonato/editar/(?P<id>\d+)/$','campeonatos.views.editar', name='editar_torneo'),
    url(r'^campeonato/encurso/$','campeonatos.views.encurso', name='encurso_torneo'),
    url(r'^campeonato/finalizados/$','campeonatos.views.finalizados', name='finalizados_torneo'),
    url(r'^campeonato/ver/(?P<id>\d+)/$','campeonatos.views.ver', name='ver_torneo'),
)

equipos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^equipo/agregar$','equipos.views.agregar', name='agregar_equipo'),
    url(r'^equipo/editar/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/editar/(?P<id>\d+)/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/lista$','equipos.views.lista', name='lista_equipo'),
)

torneos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^cuenta/", include("account.urls")),
    #Include de las aplicaciones de las urls
    url(r'^', include('arbitros.urls', namespace="arbitros")),
    url(r'^', include('campeonatos.urls', namespace="campeonatos")),
    url(r'^', include('complejos.urls', namespace="complejos")),
    url(r'^', include('equipos.urls', namespace="equipos")),
    url(r'^', include('jugadores.urls', namespace="jugadores")),
    url(r'^', include('usuario.urls', namespace="usuarios")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torneos/templates/perfil/index.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h2>{% trans "Panel de administración de sus aplicaciones" %}</h2>

    <p>
    <div class="container">
    <h2></h2>
    <div class="row form-group product-chooser">
    
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="product-chooser-item selected">
                <img src="{{ STATIC_URL }}images/torneos.png" class="img-rounded col-xs-4 col-sm-4 col-md-12 col-lg-12" alt="Mobile and Desktop">
                <div class="col-xs-8 col-sm-8 col-md-12 col-lg-12">
                    <span class="title">Torneos:</span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:agregar_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Torneo</a></span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:encurso_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Torneos en curso</a></span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:finalizados_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Torneos finalizados</a></span>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="product-chooser-item">
                <img src="{{ STATIC_URL }}images/equipos.png" class="img-rounded col-xs-4 col-sm-4 col-md-12 col-lg-12" alt="Desktop">
                <div class="col-xs-8 col-sm-8 col-md-12 col-lg-12">
                    <span class="title">Equipos</span>
                    </br>
                    <span class="description"> <a href="{% url 'equipos:agregar_equipo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Equipo</a></span>
                    </br>
                    <span class="description"><a href="{% url 'equipos:lista_equipo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Editar Equipos</a></span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:agregar_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Torneos finalizados</a></span>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="product-chooser-item">
                <img src="{{ STATIC_URL }}images/jugadores.png" class="img-rounded col-xs-4 col-sm-4 col-md-12 col-lg-12" alt="Mobile">
                <div class="col-xs-8 col-sm-8 col-md-12 col-lg-12">
                    <span class="title">Jugadores</span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:agregar_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Jugador</a></span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:encurso_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Editar Jugadores</a></span>
                    </br>
                    <span class="description"><a href="{% url 'campeonatos:agregar_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Torneos finalizados</a></span>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        
    </div>
</p>
{% endblock %}