campeonatos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^campeonato/agregar$','campeonatos.views.agregar', name='agregar_torneo'),
    url(r'^campeonato/editar/$','campeonatos.views.editar', name='editar_torneo'),
    url(r'^campeonato/editar/(?P<id>\d+)/$','campeonatos.views.editar', name='editar_torneo'),
    url(r'^campeonato/encurso/$','campeonatos.views.encurso', name='encurso_torneo'),
    url(r'^campeonato/finalizados/$','campeonatos.views.finalizados', name='finalizados_torneo'),
    url(r'^campeonato/ver/(?P<id>\d+)/$','campeonatos.views.ver', name='ver_torneo'),
)

equipos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

urlpatterns = patterns("",
    url(r'^equipo/agregar$','equipos.views.agregar', name='agregar_equipo'),
    url(r'^equipo/editar/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/editar/(?P<id>\d+)/$','equipos.views.editar', name='editar_equipo'),
    url(r'^equipo/lista$','equipos.views.lista', name='lista_equipo'),
)

torneos/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = patterns("",
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^cuenta/", include("account.urls")),
    #Include de las aplicaciones de las urls
    url(r'^', include('arbitros.urls', namespace="arbitros")),
    url(r'^', include('campeonatos.urls', namespace="campeonatos")),
    url(r'^', include('complejos.urls', namespace="complejos")),
    url(r'^', include('equipos.urls', namespace="equipos")),
    url(r'^', include('jugadores.urls', namespace="jugadores")),
    url(r'^', include('usuario.urls', namespace="usuarios")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campeonatos/models.py
from django.db import models
from django.utils.encoding import smart_unicode
from django.contrib.auth.models import User
from complejos.models import Complejo
from equipos.models import Equipo

# Create your models here.
class Campeonato(models.Model):
    nombre = models.CharField(max_length=120, null=False, )
    fecha_inicio = models.DateField(blank=True)
    cantidad_equipos = models.IntegerField(blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    complejo_id = models.ForeignKey(Complejo)
    estado_torneo = models.BooleanField(default=1)
    equipos = models.ManyToManyField(Equipo, blank=True)

    def is_active(self):
        return bool(self.active_status)

    def __unicode__(self):
        return smart_unicode(self.nombre)

campeonatos/forms.py
from django import forms

from .models import Campeonato
from equipos.models import Equipo
from django.contrib.auth.models import User

class CampeonatoForm(forms.ModelForm):
    equipos = forms.ModelMultipleChoiceField(queryset = Equipo.objects.all().filter(complejo_id__user = 1), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Campeonato

class CampeonatoPublicForm(forms.ModelForm):
    equipos = forms.ModelMultipleChoiceField(queryset = Equipo.objects.all(), widget=forms.CheckboxSelectMultiple)

campeonatos/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.views.generic import TemplateView
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .forms import CampeonatoForm
from .models import Campeonato
from complejos.forms import ComplejoPublicForm, ComplejoForm
from complejos.models import Complejo
from equipos.models import Equipo
from django import forms

# Create your views here.
@login_required
def agregar(request):
    logged_user = request.user.id
    if request.method == "POST":
        form = CampeonatoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('usuarios:perfil')
        else:
            print form.errors
    else:
        form = CampeonatoForm()
    return render_to_response("campeonato/agregar.html", {'form': form, 'user': logged_user}, context_instance=RequestContext(request))

@login_required
def editar(request, id=None):
    #Obtengo el objeto de acuerdo al id
    if id:
        campeonato_objeto =  get_object_or_404(Campeonato, id=id, complejo_id__user=request.user)
    else:
        campeonato_objeto = Campeonato(id=request.id)

    if request.method == "POST":
        campeonato_form = CampeonatoForm(request.POST, instance=campeonato_objeto)
        if campeonato_form.is_valid():
            campeonato_form.save()
            return redirect('usuarios:perfil')
    else:
        campeonato_form = CampeonatoForm(instance=campeonato_objeto)
    #Renderizo la vista y paso el objeto con los valores a editar
    return render_to_response("campeonato/editar.html", {'form': campeonato_form}, context_instance=RequestContext(request))

@login_required
def ver(request, id=None):
    #complejos = Complejo.objects.all().filter(id=id, user__id = request.user.id)
    campeonatos =  get_object_or_404(Campeonato, id=id, complejo_id__user=request.user)
    equipos = Equipo.objects.all().filter(complejo_id=campeonatos.id, complejo_id__user=request.user)
    logged_user = request.user.id
    return render_to_response("campeonato/ver.html", {'campeonatos': campeonatos, 'user': logged_user, 'equipos':equipos}, context_instance=RequestContext(request))

@login_required
def encurso(request):
    campeonatos = Campeonato.objects.all().filter(complejo_id__user = request.user.id, estado_torneo=1)
    form = CampeonatoForm()
    logged_user = request.user.id
    return render_to_response("campeonato/encurso.html", {'form': form, 'user': logged_user, 'campeonatos':campeonatos}, context_instance=RequestContext(request))

@login_required
def finalizados(request):
    campeonatos = Campeonato.objects.all().filter(complejo_id__user = request.user.id, estado_torneo=0)
    form = CampeonatoForm()
    logged_user = request.user.id
    return render_to_response("campeonato/encurso.html", {'form': form, 'user': logged_user, 'campeonatos':campeonatos}, context_instance=RequestContext(request))

torneos/templates/campeonato/agregar.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    

    <h2>{% trans "Administración de tus torneos" %}</h2>
    <p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ user }}"/>
            <input type="submit" value="Submit" />
        </form>
    </p>
{% endblock %}

torneos/templates/campeonato/agregar_equipo.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h2>{% trans "Agregar equipo al torneo" %}</h2>
    <p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" value="{{ user }}"/>
            <input type="submit" value="Submit" />
        </form>
    </p>
{% endblock %}

torneos/templates/campeonato/editar.html
 {% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    

     <form method="post">{% csrf_token %}

         {{ form.as_p }}

         <input type="hidden" name="id_complejo" value="1"/>
         <a href="#">Cancelar</a> <input type="submit" value="Guardar" />

    </form>
{% endblock %}

torneos/templates/campeonato/encurso.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h2>{% trans "Administración de tus torneos" %}</h2>

    <p>
        <div class="container">
            <hr>
            <div class="row">
                <div class="panel panel-primary filterable">
                    <div class="panel-heading">
                        <h3 class="panel-title">Torneos
                            <div class="pull-right">
                                <a href="{% url 'campeonatos:agregar_torneo' %}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Torneo</a>
                           </div>
                        </h3>
                    </div>
                    <table class="table">
                        <thead>
                            <tr class="filters">
                                <th><label>Nombre</label></th>
                                <th><label>Dirección</label></th>
                                <th><label>Teléfono</label></th>
                                <th><label>Editar</label></th>
                                <th><label>Ver</label></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for campeonato in  campeonatos %}
                            <tr>
                                <td>{{ campeonato.nombre }}</td>
                                <td>{{ campeonato.direccion }}</td>
                                <td>{{ campeonato.telefono }}</td>
                                <td>
                                     <a href="{% url  'campeonatos:editar_torneo' campeonato.id  %}" class="btn btn-default btn-xs btn-filter">Editar</a> 
                                </td>
                                <td>
                                    <a href="{% url  'campeonatos:ver_torneo' campeonato.id  %}" class="btn btn-default btn-xs btn-filter">Ver</a> 
                                </td>                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </p>
{% endblock %}

torneos/templates/campeonato/ver.html
 {% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    <h2>Información torneo</h2>
        {{ campeonatos.nombre }}
        {{ campeonatos.direccion }}
        {{ campeonatos.telefono }}
    <h2>Equipos</h2>
        <a href="{% url 'campeonatos:agregar_equipo' campeonatos.id%}" class="btn btn-default btn-xs btn-filter"><span class="glyphicon glyphicon-plus"></span> Agregar Equipo</a>
        {% for equipo in  equipos %}
                {{ equipo.nombre }}
         {% endfor %}
{% endblock %}